package router

import (
	"net/http"

	_ "github.com/anhaya/go-sample-api/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/anhaya/go-sample-api/internal/app/handler"
	"github.com/anhaya/go-sample-api/internal/app/middleware"
	"github.com/gorilla/mux"
	httpSwagger "github.com/swaggo/http-swagger"
	"github.com/urfave/negroni"
)

// @title Transaction API
// @version 1.0
// @description This is a sample service for managing transactions
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host localhost:8081
// @BasePath /
func NewRouter(accountHandler handler.AccountHandler, transactionHandler handler.TransactionHandler) http.Handler {
	//Initiate router
	router := mux.NewRouter()

	//Initiate negroni (easier to work with middleware)
	negroni := negroni.New(negroni.HandlerFunc(middleware.Cors))
	negroni.UseHandler(router)

	//Set handler for APIs
	router.HandleFunc("/accounts", accountHandler.Create).Methods("POST")
	router.HandleFunc("/accounts/{accountId}", accountHandler.Get).Methods("GET")
	router.HandleFunc("/transactions", transactionHandler.Create).Methods("POST")
	router.PathPrefix("/swagger/").Handler(httpSwagger.WrapHandler)

	return router
}
